# Generated by Django 5.0.6 on 2024-07-04 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_usuarios', '0002_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='nascimento',
            field=models.DateField(auto_now=True, verbose_name='Nascimento'),
        ),
    ]
